backend:
  name: git-gateway
  accept_roles:
    - admin
    - editor
media_folder: theme/assets/images
public_folder: /assets/images
collections:
  - name: pages
    label: Pages
    identifier_field: title
    extension: md
    create: false
    delete: false
    slug: '{{slug}}'
    editor:
      preview: false
    folder: cms/pages
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Layout
        widget: hidden
        name: layout
        default: '{{slug}}.html'
      - &ref_0
        label: Seo
        name: seo
        widget: object
        collapsed: true
        fields:
          - label: Title
            name: title
            widget: string
            required: false
          - label: Description
            name: description
            widget: string
            required: false
          - label: No index
            name: noindex
            widget: boolean
            default: false
            required: false
          - label: Open Graph Title
            name: og:title
            widget: string
            required: false
          - label: Open Graph Image
            name: og:image
            widget: image
            required: false
            media_library:
              config:
                multiple: false
          - label: Twitter Title
            name: twitter:title
            widget: string
            default: summary
            required: false
          - label: Twitter Card
            name: twitter:card
            widget: string
            default: summary
            required: false
          - label: Twitter Site
            name: twitter:site
            widget: string
            required: false
          - label: Twitter Creator
            name: twitter:creator
            widget: string
            required: false
          - label: Additional HTML tags
            name: additional_tags
            widget: text
            required: false
  - name: project
    label: Projects
    folder: cms/project
    create: true
    identifier_field: name
    extension: md
    slug: '{{slug}}'
    fields:
      - hint: ''
        name: title
        label: Name
        widget: string
        required: true
      - hint: ''
        name: created-on
        label: Created On
        widget: datetime
        required: false
      - hint: ''
        name: updated-on
        label: Updated On
        widget: datetime
        required: false
      - hint: ''
        name: published-on
        label: Published On
        widget: datetime
        required: false
      - label: Where it began
        name: body
        widget: markdown
        required: false
      - hint: ''
        name: f_client
        label: Client
        widget: string
        required: false
      - hint: ''
        name: f_project-category
        label: Project Category
        widget: string
        required: false
      - hint: ''
        name: f_duration
        label: Duration
        widget: string
        required: false
      - hint: '2020'
        name: f_year-of-project
        label: Year of project
        widget: string
        required: false
      - hint: Used on project list grid
        name: f_main-project-image
        label: Project Image
        widget: object
        required: false
        fields:
          - hint: ''
            name: url
            label: Image
            widget: image
            required: false
            allow_multiple: false
          - hint: Image Alt
            name: alt
            label: alt
            widget: string
            required: false
      - hint: ''
        name: f_the-challenge
        label: Challenge
        widget: string
        required: false
      - hint: ''
        name: f_title-2
        label: Goal
        widget: string
        required: false
      - hint: ''
        name: f_gif-single-column
        label: GIF Single column
        widget: object
        required: false
        fields:
          - hint: ''
            name: url
            label: Image
            widget: image
            required: false
            allow_multiple: false
          - hint: Image Alt
            name: alt
            label: alt
            widget: string
            required: false
      - hint: ''
        name: f_vimeo-code
        label: Vimeo code
        widget: string
        required: false
      - hint: ''
        name: f_single-column-image
        label: Single column image
        widget: object
        required: false
        fields:
          - hint: ''
            name: url
            label: Image
            widget: image
            required: false
            allow_multiple: false
          - hint: Image Alt
            name: alt
            label: alt
            widget: string
            required: false
      - hint: ''
        name: f_project-summary
        label: User research
        widget: text
        required: false
      - hint: ''
        name: f_prototype-image
        label: Prototype image
        widget: object
        required: false
        fields:
          - hint: ''
            name: url
            label: Image
            widget: image
            required: false
            allow_multiple: false
          - hint: Image Alt
            name: alt
            label: alt
            widget: string
            required: false
      - hint: ''
        name: f_external-resource
        label: External resource
        widget: string
        required: false
      - hint: ''
        name: f_prototype-link
        label: Prototype link
        widget: string
        required: false
      - hint: ''
        name: f_two-img-col-1
        label: two img col 1
        widget: object
        required: false
        fields:
          - hint: ''
            name: url
            label: Image
            widget: image
            required: false
            allow_multiple: false
          - hint: Image Alt
            name: alt
            label: alt
            widget: string
            required: false
      - hint: ''
        name: f_two-img-col-2
        label: two img col 2
        widget: object
        required: false
        fields:
          - hint: ''
            name: url
            label: Image
            widget: image
            required: false
            allow_multiple: false
          - hint: Image Alt
            name: alt
            label: alt
            widget: string
            required: false
      - hint: ''
        name: f_full-width-image
        label: Full-width image
        widget: object
        required: false
        fields:
          - hint: ''
            name: url
            label: Image
            widget: image
            required: false
            allow_multiple: false
          - hint: Image Alt
            name: alt
            label: alt
            widget: string
            required: false
      - hint: ''
        name: f_multi-images
        label: Multi-images
        widget: list
        required: false
        fields:
          - hint: ''
            name: url
            label: Image
            widget: image
            required: false
            allow_multiple: false
          - hint: Image Alt
            name: alt
            label: alt
            widget: string
            required: false
      - hint: ''
        name: f_conclusion-img
        label: Conclusion img
        widget: object
        required: false
        fields:
          - hint: ''
            name: url
            label: Image
            widget: image
            required: false
            allow_multiple: false
          - hint: Image Alt
            name: alt
            label: alt
            widget: string
            required: false
      - hint: ''
        name: f_conclusion-responsibilities
        label: Conclusion summary
        widget: markdown
        required: false
      - hint: ''
        name: f_live-site
        label: Live site
        widget: string
        required: false
      - hint: ''
        name: f_full-case-study
        label: Full case study
        widget: string
        required: false
      - hint: ''
        name: f_featured-project
        label: Featured Project?
        widget: boolean
        required: false
      - hint: ''
        name: f_custom-sort-order
        label: Custom sort order
        widget: number
        required: false
      - hint: ''
        name: f_next
        label: Next
        widget: relation
        required: false
        collection: project
        value_field: cms/project/{{slug}}.md
        search_fields:
          - slug
          - name
        display_fields:
          - title
        multiple: false
      - hint: ''
        name: f_credits-1-col
        label: Credits 1 col
        widget: markdown
        required: false
      - hint: ''
        name: f_credits-2-col
        label: Credits 2 col
        widget: markdown
        required: false
      - hint: ''
        name: f_credits-3-col
        label: Credits 3 col
        widget: markdown
        required: false
      - hint: ''
        name: f_project-alt-text
        label: Project alt text
        widget: text
        required: false
      - label: Tags
        widget: hidden
        name: tags
        default: project
      - label: Layout
        widget: hidden
        name: layout
        default: '[project].html'
      - label: Publish Date
        name: date
        widget: datetime
      - *ref_0
  - label: Theme Settings
    name: settings
    identifier_field: title
    extension: json
    create: false
    delete: false
    slug: '{{slug}}'
    editor:
      preview: false
    files:
      - label: General
        name: site
        file: cms/_data/settings/site.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: General
          - hint: Full domain url (needed for a correct sitemap file)
            name: domain
            label: Domain
            widget: string
            required: false
          - name: favicon
            label: Favicon
            widget: image
            allow_multiple: false
            required: false
          - name: apple_touch_icon
            label: Apple Touch Icon
            widget: image
            allow_multiple: false
            required: false
          - name: header_additional_content
            label: Additional Content Header
            hint: Content here will be placed before </head> tag
            widget: text
            required: false
          - name: footer_additional_content
            label: Additional Content Footer
            hint: Content here will be placed before </body> tag
            widget: text
            required: false
          - name: images_optimization
            label: Images Optimization
            widget: object
            collapsed: false
            fields:
              - label: Image Formats
                name: formats
                widget: select
                multiple: true
                options:
                  - label: Avif
                    value: avif
                  - label: Webp
                    value: webp
              - label: Image Dimensions
                name: dimensions
                widget: select
                multiple: true
                options:
                  - label: '500'
                    value: 500
                  - label: '800'
                    value: 800
                  - label: '1080'
                    value: 1080
                  - label: '1600'
                    value: 1600
                  - label: '2000'
                    value: 2000
                  - label: '2600'
                    value: 2600
      - label: Colors
        name: colors
        file: cms/_data/colors.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Colors
publish_mode: editorial_workflow
